stages:
  - build
  - test
  - deploy

default: 
  image: openjdk:15-jdk

build-job:
  stage: build
  script:
    - ./gradlew assemble

test-job:
  stage: test
  script:
    - ./gradlew test

deploy-job:
  stage: deploy
  script:
    - echo "deploy"
 


